language: generic

services:
  - docker

before_install:
  - docker pull berkgokden/sbt-base:v0.2
  - docker run -d --name builder -v $(pwd):/src -e BINTRAY_USER=$BINTRAY_USER -e BINTRAY_PASS=$BINTRAY_PASS berkgokden/sbt-base:v0.2 sleep infinity

jobs:
  include:
    - stage: test
      script: docker exec -it builder sbt clean test
    - stage: deploy
      # require the branch name to be master
      if: branch = master
      script: docker exec -it builder sbt publish